import fs from "node:fs/promises"
import path from "node:path"
import peggy from "peggy"

const rootDir = path.resolve(import.meta.dirname, "..")
const grammarPath = path.join(rootDir, "src/core/parser/grammar.peggy")
const outputPath = path.join(rootDir, "src/core/parser/generated-parser.ts")

const grammar = await fs.readFile(grammarPath, "utf8")
const source = peggy.generate(grammar, {
  format: "es",
  output: "source"
})

await fs.writeFile(
  outputPath,
  `/* eslint-disable */\n/* auto-generated by scripts/generate-parser.mjs */\n${source}\n`,
  "utf8"
)
